import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "@/components/ScrollSmooth";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import { Analytics } from "@vercel/analytics/next"
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
          <SmoothScroll>{children}</SmoothScroll>
          <Toaster className="fixed top-4 right-4" theme="dark" position="top-right" />
          <Analytics />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
